import { createContext, useContext, useState } from 'react'
import type { ReactNode } from 'react'
import { NOW } from '../../utils/now'

export interface Pranesimas {
  id: string
  functionalLocation: string
  gpsCoordinates: string
  techObject: string
  faultType: string
  notes: string
  location: { lat: number; lng: number }
  photos: string[]
  reporter: string
  createdAt: string
  createdDate: string
  isSeeded?: boolean
  isNew?: boolean
  pinType?: 'notification' | 'work_order'
  workOrderStatus?: 'planned' | 'backlog' | 'in_progress' | 'done' | 'overdue' | 'pending_approval'
  woType?: string
  kelias?: string
  woHistory?: { date: string; duration: string; senior: string }[]
  aptarnavimoDaznas?: string
  woTeam?: string[]
  woSeniorName?: string
  woJobTime?: string
  woCompletionDate?: string
  woMaterials?: string[]
  woOperation?: string
  completionReport?: {
    faultReason: string
    materialsYn: string
    material: string
    amount: string
    notes: string
    elapsed: number
    completedAt: string
  }
}

interface ContextType {
  pranesimai: Pranesimas[]
  addPranesimas: (p: Omit<Pranesimas, 'id' | 'createdAt' | 'reporter' | 'createdDate'>) => void
  removePranesimas: (id: string) => void
  markAsRead: (id: string) => void
  updateWorkOrderStatus: (id: string, status: NonNullable<Pranesimas['workOrderStatus']>, report?: Pranesimas['completionReport']) => void
  updateWorkOrder: (id: string, fields: Partial<Pranesimas>) => void
}

const PranesiamaiContext = createContext<ContextType>({
  pranesimai: [],
  addPranesimas: () => {},
  removePranesimas: () => {},
  markAsRead: () => {},
  updateWorkOrderStatus: () => {},
  updateWorkOrder: () => {},
})

const initialPranesimai: Pranesimas[] = [
  {
    isSeeded: true,
    id: 'seed-1',
    isNew: true,
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.640204, 25.227166',
    techObject: 'Išleidžiamasis šviesoforas L1',
    faultType: 'Šviesoforo defektas',
    notes: 'Dūseikių gel. blogas šviesaforo matomumas',
    location: { lat: 54.640204, lng: 25.227166 },
    photos: ['/images/railway-signal-snow.jpg'],
    reporter: 'Tomas Kazlauskas',
    createdAt: '11:45',
    createdDate: '2026-04-13',
  },
  {
    isSeeded: true,
    id: 'seed-2',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.642100, 25.224800',
    techObject: 'Priimamasis šviesoforas N2',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Šviesoforas neįsijungia po perjungimo',
    location: { lat: 54.6421, lng: 25.2248 },
    photos: [],
    reporter: 'Mindaugas Petrauskas',
    createdAt: '07:42',
    createdDate: '2026-04-10',
  },
  {
    isSeeded: true,
    id: 'seed-3',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.638900, 25.230100',
    techObject: 'Manevrinė strėlė M14',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Aptikimo kilpa nefiksuoja riedmens',
    location: { lat: 54.6389, lng: 25.2301 },
    photos: [],
    reporter: 'Rolandas Jankauskas',
    createdAt: '06:55',
    createdDate: '2026-04-09',
  },
  {
    isSeeded: true,
    id: 'seed-10',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    woType: 'Planinis',
    kelias: 'Pagrindinis',
    aptarnavimoDaznas: 'Kas savaitę',
    functionalLocation: 'Šiaulių regiono kelių priežiūra',
    gpsCoordinates: '55.934032, 23.313716',
    techObject: 'Iešmai',
    faultType: 'Periodinė Iešmų patikra',
    notes: '',
    location: { lat: 55.934032, lng: 23.313716 },
    photos: [],
    reporter: 'Planuotojas',
    createdAt: '08:00',
    createdDate: '2026-05-01',
  },
  {
    isSeeded: true,
    id: 'seed-11',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    woType: 'Kas 1 mėnuo',
    kelias: 'Atvykimo',
    aptarnavimoDaznas: 'Kas mėnesį',
    functionalLocation: 'Šiaulių regiono kelių priežiūra',
    gpsCoordinates: '55.934032, 23.313716',
    techObject: 'Iešmai',
    faultType: 'Periodinė Iešmų patikra',
    notes: '',
    location: { lat: 55.934032, lng: 23.313716 },
    photos: [],
    reporter: 'Planuotojas',
    createdAt: '08:00',
    createdDate: '2026-05-01',
  },
  {
    isSeeded: true,
    id: 'seed-4',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.641500, 25.221300',
    techObject: 'Išleidžiamasis šviesoforas L3',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Pertrauktas valdymo kabelis prie posto',
    location: { lat: 54.6415, lng: 25.2213 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:03',
    createdDate: '2026-04-10',
  },
  {
    isSeeded: true,
    id: 'seed-5',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.637800, 25.226400',
    techObject: 'EC valdymo įranga VP-1',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Įranga neatsako į komandas iš centrinio posto',
    location: { lat: 54.6378, lng: 25.2264 },
    photos: ['/images/railway-signal-snow.jpg'],
    reporter: 'Darius Stankevičius',
    createdAt: '10:17',
    createdDate: '2026-04-10',
  },
  {
    isSeeded: true,
    id: 'seed-6',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.643200, 25.232700',
    techObject: 'Manevrinė strėlė M8',
    faultType: 'Šviesoforo defektas',
    notes: 'Žalias signalas neįsijungia',
    location: { lat: 54.6432, lng: 25.2327 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '11:44',
    createdDate: '2026-04-10',
  },
  {
    isSeeded: true,
    id: 'seed-7',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.636500, 25.223900',
    techObject: 'RAKP sistemos modulis R2',
    faultType: 'RAKP sistemos defektas',
    notes: 'Ryšio sutrikimas su centrine stotimi',
    location: { lat: 54.6365, lng: 25.2239 },
    photos: [],
    reporter: 'Valdas Mockus',
    createdAt: '05:30',
    createdDate: '2026-04-09',
  },
  {
    isSeeded: true,
    id: 'seed-8',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.644700, 25.228900',
    techObject: 'Priimamasis šviesoforas N4',
    faultType: 'Kontrolės praradimas',
    notes: 'Prarastas šviesoforo būsenos kontrolės signalas',
    location: { lat: 54.6447, lng: 25.2289 },
    photos: [],
    reporter: 'Saulius Butkus',
    createdAt: '14:22',
    createdDate: '2026-04-09',
  },
  {
    isSeeded: true,
    id: 'seed-9',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.639600, 25.218500',
    techObject: 'SIS blokas S1',
    faultType: 'SIS defektas',
    notes: 'SIS sistema neužtikrina saugos funkcijų',
    location: { lat: 54.6396, lng: 25.2185 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '16:08',
    createdDate: '2026-04-09',
  },
  {
    isSeeded: true,
    id: 'seed-10',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.645900, 25.224100',
    techObject: 'Išleidžiamasis šviesoforas L5',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Signalo lempa veikia su pertrūkiais',
    location: { lat: 54.6459, lng: 25.2241 },
    photos: [],
    reporter: 'Edvinas Žukauskas',
    createdAt: '08:50',
    createdDate: '2026-04-08',
  },
  {
    isSeeded: true,
    id: 'seed-11',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.638200, 25.233800',
    techObject: 'Manevrinė strėlė M21',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Strėlės padėties daviklis neveikia',
    location: { lat: 54.6382, lng: 25.2338 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '12:35',
    createdDate: '2026-04-08',
  },
  {
    isSeeded: true,
    id: 'seed-12',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.642800, 25.219700',
    techObject: 'EC valdymo įranga VP-3',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Drėgmė pažeidė kabelių jungtis',
    location: { lat: 54.6428, lng: 25.2197 },
    photos: [],
    reporter: 'Gintaras Paulauskas',
    createdAt: '07:15',
    createdDate: '2026-04-08',
  },
  // Today (2026-04-13)
  {
    isSeeded: true,
    id: 'seed-13',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.640800, 25.226000',
    techObject: 'Priimamasis šviesoforas N6',
    faultType: 'Šviesoforo defektas',
    notes: 'Raudonas signalas nepersijungia',
    location: { lat: 54.6408, lng: 25.2260 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '07:05',
    createdDate: '2026-04-13',
  },
  {
    isSeeded: true,
    id: 'seed-14',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.639000, 25.229500',
    techObject: 'Manevrinė strėlė M3',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Aptikimo kilpa rodo klaidingą signalą',
    location: { lat: 54.6390, lng: 25.2295 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:30',
    createdDate: '2026-04-13',
  },
  {
    isSeeded: true,
    id: 'seed-22',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.641800, 25.225200',
    techObject: 'RAKP sistemos modulis R6',
    faultType: 'RAKP sistemos defektas',
    notes: 'Modulis perkraunamas kas 30 minučių',
    location: { lat: 54.6418, lng: 25.2252 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '11:45',
    createdDate: '2026-04-13',
  },
  {
    isSeeded: true,
    id: 'seed-23',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.637500, 25.222700',
    techObject: 'Išleidžiamasis šviesoforas L9',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Pažeistas apsauginis kabelio apvalkalas',
    location: { lat: 54.6375, lng: 25.2227 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '13:10',
    createdDate: '2026-04-13',
  },
  // Today (2026-04-14)
  {
    isSeeded: true,
    id: 'seed-27',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.640034, 25.226408',
    techObject: 'Išleidžiamasis šviesoforas L1',
    faultType: 'Šviesoforo defektas',
    notes: 'Dūseikių gel. blogas šviesaforo matomumas',
    location: { lat: 54.640034, lng: 25.226408 },
    photos: ['/images/railway-signal-snow.jpg'],
    reporter: 'Tech darbuotojas',
    createdAt: '13:00',
    createdDate: '2026-04-14',
    woTeam: ['Kęstutis Norvaišas', 'Povilas Stankūnas', 'Henrikas Jokubaitis', 'Ričardas Butkevičius'],
    woSeniorName: 'Kęstutis Norvaišas',
    woCompletionDate: '2026-04-14',
    woMaterials: ['Šviesaforo medžiagos'],
    woOperation: 'Atlikti techninę apžiūrą',
  },
  {
    isSeeded: true,
    id: 'seed-28',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.643500, 25.222100',
    techObject: 'Kabelių kanalas km 12+400',
    faultType: 'Kabelių defektas',
    notes: 'Pažeista kabelių izoliacija po liūties',
    location: { lat: 54.6435, lng: 25.2221 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:45',
    createdDate: '2026-04-14',
    woTeam: ['Ramūnas Žilinskas', 'Povilas Stankūnas', 'Henrikas Jokubaitis'],
    woSeniorName: 'Ramūnas Žilinskas',
    woCompletionDate: '2026-04-14',
    woMaterials: ['Kabeliai'],
    woOperation: 'Pakeisti kabelius',
  },
  {
    isSeeded: true,
    id: 'seed-29',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.639800, 25.227600',
    techObject: 'Iešmas Nr. 7',
    faultType: 'Iešmo gedimas',
    notes: 'Iešmas stringa pervedimo metu',
    location: { lat: 54.6398, lng: 25.2276 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '11:00',
    createdDate: '2026-04-14',
    woCompletionDate: '2026-04-14',
    woMaterials: [],
    woOperation: '',
  },
  {
    isSeeded: true,
    id: 'seed-30',
    pinType: 'work_order',
    workOrderStatus: 'overdue',
    functionalLocation: 'Vilniaus gel. stotis',
    gpsCoordinates: '54.669300, 25.279700',
    techObject: 'Transformatorius T-5',
    faultType: 'Elektros gedimas',
    notes: 'Transformatorius neveikia, terminas praleistas',
    location: { lat: 54.6693, lng: 25.2797 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:00',
    createdDate: '2026-04-10',
    woCompletionDate: '2026-04-10',
    woMaterials: [],
    woOperation: 'Pakeisti defektuotą įrangą',
  },
  {
    isSeeded: true,
    id: 'seed-31',
    pinType: 'work_order',
    workOrderStatus: 'pending_approval',
    functionalLocation: 'Kauno gel. stotis',
    gpsCoordinates: '54.897200, 23.923200',
    techObject: 'Relė AR-22',
    faultType: 'Apsaugos relės gedimas',
    notes: 'Darbai atlikti, laukiama vadovo patvirtinimo',
    location: { lat: 54.8972, lng: 23.9232 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:30',
    createdDate: '2026-04-14',
    woCompletionDate: '2026-04-14',
    woMaterials: ['Signalizacijos moduliai'],
    woOperation: 'Pakeisti defektuotą įrangą',
  },
  // This week (2026-04-11)
  {
    isSeeded: true,
    id: 'seed-15',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.641200, 25.223400',
    techObject: 'SIS blokas S3',
    faultType: 'SIS defektas',
    notes: 'Saugos funkcija neaktyvuojama laiku',
    location: { lat: 54.6412, lng: 25.2234 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '11:20',
    createdDate: '2026-04-11',
  },
  {
    isSeeded: true,
    id: 'seed-16',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.643800, 25.221800',
    techObject: 'RAKP sistemos modulis R4',
    faultType: 'RAKP sistemos defektas',
    notes: 'Modulis neužmezga ryšio su serveriu',
    location: { lat: 54.6438, lng: 25.2218 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '14:50',
    createdDate: '2026-04-12',
  },
  {
    isSeeded: true,
    id: 'seed-24',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.644000, 25.230500',
    techObject: 'EC valdymo įranga VP-7',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Ryšio praradimas su lauko moduliu',
    location: { lat: 54.6440, lng: 25.2305 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:15',
    createdDate: '2026-04-11',
  },
  {
    isSeeded: true,
    id: 'seed-25',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.636800, 25.227300',
    techObject: 'Manevrinė strėlė M25',
    faultType: 'Šviesoforo defektas',
    notes: 'Strėlės padėties indikatorius rodo klaidą',
    location: { lat: 54.6368, lng: 25.2273 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:55',
    createdDate: '2026-04-12',
  },
  {
    isSeeded: true,
    id: 'seed-26',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.643500, 25.224000',
    techObject: 'SIS blokas S7',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Signalo vėlavimas viršija leistinas ribas',
    location: { lat: 54.6435, lng: 25.2240 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '16:30',
    createdDate: '2026-04-11',
  },
  // This month, earlier (2026-04-02)
  {
    isSeeded: true,
    id: 'seed-17',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.637200, 25.231200',
    techObject: 'Išleidžiamasis šviesoforas L7',
    faultType: 'Kontrolės praradimas',
    notes: 'Šviesoforo būsena neatnaujinama',
    location: { lat: 54.6372, lng: 25.2312 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:40',
    createdDate: '2026-04-02',
  },
  {
    isSeeded: true,
    id: 'seed-18',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.645200, 25.226800',
    techObject: 'EC valdymo įranga VP-5',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Įrangos gedimas po perkrovimo',
    location: { lat: 54.6452, lng: 25.2268 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '15:10',
    createdDate: '2026-04-03',
  },
  // This year, earlier months
  {
    isSeeded: true,
    id: 'seed-19',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.640000, 25.224500',
    techObject: 'Manevrinė strėlė M17',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Trumpasis jungimas valdymo kabelyje',
    location: { lat: 54.6400, lng: 25.2245 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:00',
    createdDate: '2026-03-15',
  },
  {
    isSeeded: true,
    id: 'seed-20',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.638500, 25.228000',
    techObject: 'Priimamasis šviesoforas N8',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Lempa neveikia šalčio sąlygomis',
    location: { lat: 54.6385, lng: 25.2280 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '13:25',
    createdDate: '2026-02-20',
  },
  {
    isSeeded: true,
    id: 'seed-21',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.642000, 25.232000',
    techObject: 'SIS blokas S5',
    faultType: 'SIS defektas',
    notes: 'Periodinis sistemos atsisakymas',
    location: { lat: 54.6420, lng: 25.2320 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:15',
    createdDate: '2026-01-08',
  },
  {
    isSeeded: true,
    id: 'w1',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6360, 25.2180',
    techObject: 'Išleidžiamasis šviesoforas L2',
    faultType: 'Šviesoforo defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6360, lng: 25.2180 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '06:30',
    createdDate: '2026-01-05',
  },
  {
    isSeeded: true,
    id: 'w2',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6370, 25.2190',
    techObject: 'Priimamasis šviesoforas N1',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6370, lng: 25.2190 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '07:15',
    createdDate: '2026-01-07',
  },
  {
    isSeeded: true,
    id: 'w3',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6380, 25.2200',
    techObject: 'Manevrinė strėlė M6',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6380, lng: 25.2200 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:00',
    createdDate: '2026-01-09',
  },
  {
    isSeeded: true,
    id: 'w4',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6390, 25.2210',
    techObject: 'EC valdymo įranga VP-2',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6390, lng: 25.2210 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:45',
    createdDate: '2026-01-12',
  },
  {
    isSeeded: true,
    id: 'w5',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6400, 25.2220',
    techObject: 'RAKP sistemos modulis R1',
    faultType: 'SIS defektas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6400, lng: 25.2220 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:30',
    createdDate: '2026-01-14',
  },
  {
    isSeeded: true,
    id: 'w6',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6410, 25.2230',
    techObject: 'SIS blokas S2',
    faultType: 'RAKP sistemos defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6410, lng: 25.2230 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:00',
    createdDate: '2026-01-16',
  },
  {
    isSeeded: true,
    id: 'w7',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6420, 25.2240',
    techObject: 'Išleidžiamasis šviesoforas L4',
    faultType: 'Kontrolės praradimas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6420, lng: 25.2240 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:50',
    createdDate: '2026-01-19',
  },
  {
    isSeeded: true,
    id: 'w8',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6430, 25.2250',
    techObject: 'Priimamasis šviesoforas N3',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6430, lng: 25.2250 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '11:30',
    createdDate: '2026-01-21',
  },
  {
    isSeeded: true,
    id: 'w9',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6440, 25.2260',
    techObject: 'Manevrinė strėlė M10',
    faultType: 'Šviesoforo defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6440, lng: 25.2260 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '12:15',
    createdDate: '2026-01-23',
  },
  {
    isSeeded: true,
    id: 'w10',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6450, 25.2270',
    techObject: 'EC valdymo įranga VP-4',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6450, lng: 25.2270 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '13:00',
    createdDate: '2026-01-26',
  },
  {
    isSeeded: true,
    id: 'w11',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6360, 25.2280',
    techObject: 'RAKP sistemos modulis R3',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6360, lng: 25.2280 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '14:20',
    createdDate: '2026-01-28',
  },
  {
    isSeeded: true,
    id: 'w12',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6370, 25.2290',
    techObject: 'SIS blokas S4',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6370, lng: 25.2290 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '15:10',
    createdDate: '2026-01-30',
  },
  {
    isSeeded: true,
    id: 'w13',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6380, 25.2180',
    techObject: 'Išleidžiamasis šviesoforas L6',
    faultType: 'SIS defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6380, lng: 25.2180 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '16:00',
    createdDate: '2026-01-31',
  },
  {
    isSeeded: true,
    id: 'w14',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6390, 25.2190',
    techObject: 'Priimamasis šviesoforas N5',
    faultType: 'RAKP sistemos defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6390, lng: 25.2190 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '06:30',
    createdDate: '2026-02-03',
  },
  {
    isSeeded: true,
    id: 'w15',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6400, 25.2200',
    techObject: 'Manevrinė strėlė M12',
    faultType: 'Kontrolės praradimas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6400, lng: 25.2200 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '07:15',
    createdDate: '2026-02-05',
  },
  {
    isSeeded: true,
    id: 'w16',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6410, 25.2210',
    techObject: 'EC valdymo įranga VP-6',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6410, lng: 25.2210 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:00',
    createdDate: '2026-02-07',
  },
  {
    isSeeded: true,
    id: 'w17',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6420, 25.2220',
    techObject: 'RAKP sistemos modulis R5',
    faultType: 'Šviesoforo defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6420, lng: 25.2220 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:45',
    createdDate: '2026-02-10',
  },
  {
    isSeeded: true,
    id: 'w18',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6430, 25.2230',
    techObject: 'SIS blokas S6',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6430, lng: 25.2230 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:30',
    createdDate: '2026-02-12',
  },
  {
    isSeeded: true,
    id: 'w19',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6440, 25.2240',
    techObject: 'Išleidžiamasis šviesoforas L2',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6440, lng: 25.2240 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:00',
    createdDate: '2026-02-14',
  },
  {
    isSeeded: true,
    id: 'w20',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6450, 25.2250',
    techObject: 'Priimamasis šviesoforas N1',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6450, lng: 25.2250 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:50',
    createdDate: '2026-02-17',
  },
  {
    isSeeded: true,
    id: 'w21',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6360, 25.2260',
    techObject: 'Manevrinė strėlė M6',
    faultType: 'SIS defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6360, lng: 25.2260 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '11:30',
    createdDate: '2026-02-19',
  },
  {
    isSeeded: true,
    id: 'w22',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6370, 25.2270',
    techObject: 'EC valdymo įranga VP-2',
    faultType: 'RAKP sistemos defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6370, lng: 25.2270 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '12:15',
    createdDate: '2026-02-23',
  },
  {
    isSeeded: true,
    id: 'w23',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6380, 25.2280',
    techObject: 'RAKP sistemos modulis R1',
    faultType: 'Kontrolės praradimas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6380, lng: 25.2280 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '13:00',
    createdDate: '2026-02-25',
  },
  {
    isSeeded: true,
    id: 'w24',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6390, 25.2290',
    techObject: 'SIS blokas S2',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6390, lng: 25.2290 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '14:20',
    createdDate: '2026-02-26',
  },
  {
    isSeeded: true,
    id: 'w25',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6400, 25.2180',
    techObject: 'Išleidžiamasis šviesoforas L4',
    faultType: 'Šviesoforo defektas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6400, lng: 25.2180 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '15:10',
    createdDate: '2026-02-28',
  },
  {
    isSeeded: true,
    id: 'w26',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6410, 25.2190',
    techObject: 'Priimamasis šviesoforas N3',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6410, lng: 25.2190 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '16:00',
    createdDate: '2026-03-02',
  },
  {
    isSeeded: true,
    id: 'w27',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6420, 25.2200',
    techObject: 'Manevrinė strėlė M10',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6420, lng: 25.2200 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '06:30',
    createdDate: '2026-03-04',
  },
  {
    isSeeded: true,
    id: 'w28',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6430, 25.2210',
    techObject: 'EC valdymo įranga VP-4',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6430, lng: 25.2210 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '07:15',
    createdDate: '2026-03-06',
  },
  {
    isSeeded: true,
    id: 'w29',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6440, 25.2220',
    techObject: 'RAKP sistemos modulis R3',
    faultType: 'SIS defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6440, lng: 25.2220 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:00',
    createdDate: '2026-03-09',
  },
  {
    isSeeded: true,
    id: 'w30',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6450, 25.2230',
    techObject: 'SIS blokas S4',
    faultType: 'RAKP sistemos defektas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6450, lng: 25.2230 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:45',
    createdDate: '2026-03-11',
  },
  {
    isSeeded: true,
    id: 'w31',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6360, 25.2240',
    techObject: 'Išleidžiamasis šviesoforas L6',
    faultType: 'Kontrolės praradimas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6360, lng: 25.2240 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:30',
    createdDate: '2026-03-13',
  },
  {
    isSeeded: true,
    id: 'w32',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6370, 25.2250',
    techObject: 'Priimamasis šviesoforas N5',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6370, lng: 25.2250 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:00',
    createdDate: '2026-03-17',
  },
  {
    isSeeded: true,
    id: 'w33',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6380, 25.2260',
    techObject: 'Manevrinė strėlė M12',
    faultType: 'Šviesoforo defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6380, lng: 25.2260 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '10:50',
    createdDate: '2026-03-19',
  },
  {
    isSeeded: true,
    id: 'w34',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6390, 25.2270',
    techObject: 'EC valdymo įranga VP-6',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6390, lng: 25.2270 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '11:30',
    createdDate: '2026-03-21',
  },
  {
    isSeeded: true,
    id: 'w35',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6400, 25.2280',
    techObject: 'RAKP sistemos modulis R5',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6400, lng: 25.2280 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '12:15',
    createdDate: '2026-03-24',
  },
  {
    isSeeded: true,
    id: 'w36',
    pinType: 'work_order',
    workOrderStatus: 'done',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6410, 25.2290',
    techObject: 'SIS blokas S6',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6410, lng: 25.2290 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '13:00',
    createdDate: '2026-03-26',
  },
  {
    isSeeded: true,
    id: 'w37',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6420, 25.2180',
    techObject: 'Išleidžiamasis šviesoforas L2',
    faultType: 'SIS defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6420, lng: 25.2180 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '14:20',
    createdDate: '2026-03-28',
  },
  {
    isSeeded: true,
    id: 'w38',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6430, 25.2190',
    techObject: 'Priimamasis šviesoforas N1',
    faultType: 'RAKP sistemos defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6430, lng: 25.2190 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '15:10',
    createdDate: '2026-03-30',
  },
  {
    isSeeded: true,
    id: 'w39',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6440, 25.2200',
    techObject: 'Manevrinė strėlė M6',
    faultType: 'Kontrolės praradimas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6440, lng: 25.2200 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '16:00',
    createdDate: '2026-04-01',
  },
  {
    isSeeded: true,
    id: 'w40',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6450, 25.2210',
    techObject: 'EC valdymo įranga VP-2',
    faultType: 'EC/MPC valdymo įrangos defektas',
    notes: 'Periodinis gedimas',
    location: { lat: 54.6450, lng: 25.2210 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '06:30',
    createdDate: '2026-04-04',
  },
  {
    isSeeded: true,
    id: 'w41',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6360, 25.2220',
    techObject: 'RAKP sistemos modulis R1',
    faultType: 'Šviesoforo defektas',
    notes: 'Gedimas nustatytas profilaktinės patikros metu',
    location: { lat: 54.6360, lng: 25.2220 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '07:15',
    createdDate: '2026-04-05',
  },
  {
    isSeeded: true,
    id: 'w42',
    pinType: 'work_order',
    workOrderStatus: 'planned',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6370, 25.2230',
    techObject: 'SIS blokas S2',
    faultType: 'Kabelių tinklo defektas',
    notes: 'Pranešta apie gedimą iš posto',
    location: { lat: 54.6370, lng: 25.2230 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:00',
    createdDate: '2026-04-06',
  },
  {
    isSeeded: true,
    id: 'w43',
    pinType: 'work_order',
    workOrderStatus: 'in_progress',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6380, 25.2240',
    techObject: 'Išleidžiamasis šviesoforas L4',
    faultType: 'Riedmens aptikimo įrangos defektas',
    notes: 'Automatinė gedimo diagnostika',
    location: { lat: 54.6380, lng: 25.2240 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '08:45',
    createdDate: '2026-04-07',
  },
  {
    isSeeded: true,
    id: 'w44',
    pinType: 'work_order',
    workOrderStatus: 'backlog',
    functionalLocation: 'Dūseikių gel. stotis',
    gpsCoordinates: '54.6390, 25.2250',
    techObject: 'Priimamasis šviesoforas N3',
    faultType: 'Signalizacijos įrangos defektas',
    notes: 'Vizualiai nustatytas gedimas',
    location: { lat: 54.6390, lng: 25.2250 },
    photos: [],
    reporter: 'Tech darbuotojas',
    createdAt: '09:30',
    createdDate: '2026-04-08',
  },
]

export function PranesiamaiProvider({ children }: { children: ReactNode }) {
  const [pranesimai, setPranesimai] = useState<Pranesimas[]>(initialPranesimai)

  const addPranesimas = (p: Omit<Pranesimas, 'id' | 'createdAt' | 'reporter' | 'createdDate'>) => {
    setPranesimai(prev => [{
      ...p,
      id: Date.now().toString(),
      reporter: 'Tech darbuotojas',
      createdAt: NOW.toLocaleTimeString('lt-LT', { hour: '2-digit', minute: '2-digit' }),
      createdDate: NOW.toISOString().slice(0, 10),
    }, ...prev])
  }

  const removePranesimas = (id: string) =>
    setPranesimai(prev => prev.filter(p => p.id !== id))

  const markAsRead = (id: string) =>
    setPranesimai(prev => prev.map(p => p.id === id ? { ...p, isNew: false } : p))

  const updateWorkOrderStatus = (id: string, status: NonNullable<Pranesimas['workOrderStatus']>, report?: Pranesimas['completionReport']) =>
    setPranesimai(prev => prev.map(p => p.id === id ? { ...p, workOrderStatus: status, ...(report && { completionReport: report }) } : p))

  const updateWorkOrder = (id: string, fields: Partial<Pranesimas>) =>
    setPranesimai(prev => prev.map(p => p.id === id ? { ...p, ...fields } : p))

  return (
    <PranesiamaiContext.Provider value={{ pranesimai, addPranesimas, removePranesimas, markAsRead, updateWorkOrderStatus, updateWorkOrder }}>
      {children}
    </PranesiamaiContext.Provider>
  )
}

export const usePranesimai = () => useContext(PranesiamaiContext)
