export const TECH_OBJECTS: string[] = [
  'Vidaus stoties valdymo įranga',
  'Valdymo spintos',
  'Valdymo įrangos patalpos',
  'Šviesoforai',
  'Stoties pastatas',
  'Stoties garsinis ryšys',
  'Skiriamieji transformatoriai',
  'Signalizacijos kabeliai',
  'Ryšių kabeliai',
  'Riedmens aptikimo įranga',
  'Pervaža 269+508',
  'Pervaža 268+036',
  'Peronas Dūseikiai I kelias',
  'MPC konteineris',
  'Linija ST-E-210-ĮMS',
  'Linija ST-4-03-ĮMS',
  'Linija RES-ĮMS',
  'Linija PS-1-RTU',
  'Linija PS-1-PS-3',
  'Linija PS-1-PS-2',
  'Linija PS-1-ĮMS (269km)',
  'Linija PS-1-ĮMS (268km)',
  'Linija PS-1-DACON katilas',
  'Linija PS-1-AS-1',
  'Linija ĮMS-GSMR F2',
  'Linija ĮMS-GSMR F1',
  'Linija atr.1S/1-atr.1S/21',
  'Kelias Nr.I šv.N-1K',
  'Kelias Nr.I 2K-šv.L',
  'Kelias Nr.I 1K-2K',
  'Kelias Nr.2 1K-2K',
  'Iešmų šildymas',
  'Iešmas Nr.2K',
  'Iešmas Nr.1K',
  'GSM-R fiksuoto ryšio pultai',
  'GSM-R bazinė stotis Dūseikiai',
  'Gatvių tipo',
  'DGA konteineris',
  'Centrinis NMŠ',
  'Autonominis el. šaltinis',
]
